# Generated by Django 5.1.11 on 2025-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="classification",
            field=models.CharField(
                blank=True,
                help_text="Segmonto Ontology classification (e.g., MainZone, DefaultLine)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enabled_line_types",
            field=models.JSONField(
                default=list,
                help_text="List of enabled line types for annotation classification",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enabled_zone_types",
            field=models.JSONField(
                default=list,
                help_text="List of enabled zone types for annotation classification",
            ),
        ),
    ]
