# Generated by Django 5.1.11 on 2025-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0002_annotation_classification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_prompts",
            field=models.JSONField(
                default=list,
                help_text="List of custom prompts with associated zones and metadata fields",
            ),
        ),
    ]
