# Generated by Django 5.1.11 on 2025-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0003_annotation_metadata_userprofile_custom_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="roboflow_api_key_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roboflow_workflow_endpoint",
            field=models.CharField(
                blank=True,
                help_text="Roboflow workflow endpoint after 'workflows/' (e.g., 'text-regions/detect-count-and-visualize')",
                max_length=500,
                null=True,
            ),
        ),
    ]
