# Generated by Django 5.1.11 on 2025-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0004_userprofile_roboflow_api_key_set_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="roboflow_workflow_endpoint",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roboflow_workflow_id",
            field=models.CharField(
                blank=True,
                help_text="Roboflow workflow ID (e.g., 'detect-count-and-visualize')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roboflow_workspace_name",
            field=models.CharField(
                blank=True,
                help_text="Roboflow workspace name (e.g., 'text-regions')",
                max_length=100,
                null=True,
            ),
        ),
    ]
