# Generated by Django 5.1.11 on 2025-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0005_remove_userprofile_roboflow_workflow_endpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_detection_mappings",
            field=models.JSONField(
                default=dict,
                help_text="Custom mappings from detection model classes to UI classifications",
            ),
        ),
    ]
