# Generated by Django 5.1.11 on 2025-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0006_userprofile_custom_detection_mappings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["reading_order", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
